import type { CSSProperties } from "react";

export const s: Record<string, CSSProperties> = {
  app: { display: "flex", height: "100dvh", width: "100vw", overflow: "hidden" },
  loginScreen: { position: "fixed", inset: 0, zIndex: 2000, display: "flex", alignItems: "center", justifyContent: "center", padding: 16, background: "rgba(0,0,0,0.45)" },
  loginCard: { borderRadius: 28, padding: 34, width: "min(520px, calc(100vw - 32px))", boxShadow: "0 30px 90px rgba(0,0,0,0.25)" },
  loginModalWrap: { position: "relative" },
  sidebar: { height: "100dvh", padding: 10, display: "flex", flexDirection: "column", gap: 12, overflow: "hidden", flexShrink: 0 },
  sidebarTop: { display: "flex", alignItems: "center", justifyContent: "space-between", gap: 8, minHeight: 50 },
  logoWrap: { display: "flex", alignItems: "center", gap: 10, minWidth: 0 },
  logoMark: { width: 34, height: 34, borderRadius: 12, color: "white", display: "flex", alignItems: "center", justifyContent: "center", fontWeight: 900 },
  logoText: { fontSize: 21, fontWeight: 900, letterSpacing: -1, whiteSpace: "nowrap" },
  collapseBtn: { width: 44, height: 44, borderRadius: 14, cursor: "pointer", fontSize: 22, background: "transparent" },
  iconNav: { display: "flex", flexDirection: "column", gap: 10 },
  iconBtn: { minHeight: 44, borderRadius: 14, cursor: "pointer", display: "flex", alignItems: "center", gap: 10, fontSize: 14, fontWeight: 800, background: "transparent", border: "1px solid transparent" },
  icon: { width: 22, textAlign: "center" },
  toolsGroup: { display: "flex", flexDirection: "column", gap: 6, borderRadius: 18, padding: 8, margin: "8px 0" },
  toolsTitle: { fontSize: 11, textTransform: "uppercase", fontWeight: 950, padding: "5px 8px 7px", borderBottom: "1px solid rgba(120,120,120,0.18)" },
  chatHistory: { flex: 1, overflowY: "auto", display: "flex", flexDirection: "column", gap: 6 },
  historyHeaderRow: { display: "flex", alignItems: "center", justifyContent: "space-between", gap: 8, padding: "2px 4px" },
  historyHeader: { fontSize: 11, textTransform: "uppercase", fontWeight: 800, opacity: 0.5 },
  clearChatsBtn: { borderRadius: 999, background: "transparent", cursor: "pointer", fontSize: 11, fontWeight: 850, padding: "5px 8px" },
  historyItem: { minHeight: 38, display: "flex", alignItems: "center", justifyContent: "space-between", borderRadius: 12, padding: "8px 8px 8px 10px", fontSize: 13, gap: 8 },
  historyTitle: { overflow: "hidden", whiteSpace: "nowrap", textOverflow: "ellipsis", flex: 1, cursor: "pointer" },
  deleteBtn: { width: 24, height: 24, borderRadius: "50%", background: "rgba(120,120,120,0.10)", cursor: "pointer", fontSize: 16, display: "flex", alignItems: "center", justifyContent: "center" },
  sidebarBottomActions: { marginTop: "auto", display: "flex", flexDirection: "column", gap: 8 },
  main: { flex: 1, minWidth: 0, height: "100dvh", display: "flex", flexDirection: "column", position: "relative", overflow: "hidden" },
  collapsedBrand: { position: "absolute", top: 22, left: 28, zIndex: 20, fontSize: 24, fontWeight: 950, letterSpacing: 2, pointerEvents: "none" },
  floatingAccountBtn: { position: "absolute", top: 18, right: 28, zIndex: 30, width: 44, height: 44, borderRadius: 14, cursor: "pointer", fontSize: 18, display: "flex", alignItems: "center", justifyContent: "center" },
  content: { flex: 1, minHeight: 0, width: "100%", display: "flex", flexDirection: "column", alignItems: "center", overflow: "hidden" },
  homeWrapper: { width: "100%", maxWidth: 720, textAlign: "center", padding: "0 22px" },
  welcomeText: { fontSize: "clamp(25px, 4vw, 38px)", fontWeight: 700, marginBottom: 30, letterSpacing: -1 },
  inputComposer: { display: "flex", flexDirection: "column", gap: 8, borderRadius: 28, padding: "8px 12px", width: "100%", minHeight: 56, boxShadow: "0 8px 24px rgba(0,0,0,0.05)" },
  searchBarInner: { display: "flex", alignItems: "center", width: "100%" },
  fileBtn: { width: 34, height: 34, background: "none", border: "none", cursor: "pointer", fontSize: 18 },
  textarea: { flex: 1, minWidth: 0, maxHeight: 140, background: "none", border: "none", outline: "none", textAlign: "center", fontSize: 16, resize: "none", padding: "10px 0" },
  sendBtn: { width: 34, height: 34, background: "none", border: "none", cursor: "pointer", fontSize: 20 },
  fileHint: { fontSize: 12, opacity: 0.58, marginTop: 12 },
  pendingFileChip: { display: "flex", alignItems: "center", gap: 10, borderRadius: 18, padding: "10px 12px", width: "100%" },
  fileIcon: { width: 36, height: 44, borderRadius: 10, color: "white", display: "flex", alignItems: "center", justifyContent: "center", fontSize: 18, fontWeight: 900, flexShrink: 0 },
  roundBtn: { width: 30, height: 30, borderRadius: "50%", border: "none", background: "rgba(120,120,120,0.16)", cursor: "pointer", fontSize: 18, lineHeight: 1 },
  muted: { fontSize: 12, opacity: 0.65, margin: "4px 0 0", lineHeight: 1.45 },
  chatView: { width: "100%", maxWidth: 940, flex: 1, minHeight: 0, display: "flex", flexDirection: "column", padding: "14px 22px", overflow: "hidden" },
  msgList: { flex: 1, minHeight: 0, overflowY: "auto", display: "flex", flexDirection: "column", gap: 18, padding: "10px 0" },
  uRow: { display: "flex", justifyContent: "flex-end", width: "100%" },
  aRow: { display: "flex", justifyContent: "flex-start", alignItems: "flex-start", gap: 12, width: "100%" },
  uBox: { padding: "13px 18px", borderRadius: "22px 22px 6px 22px", maxWidth: "78%", fontSize: 15, whiteSpace: "pre-wrap", overflowWrap: "anywhere", lineHeight: 1.55 },
  aBox: { padding: "18px 20px", borderRadius: "8px 22px 22px 22px", lineHeight: 1.72, fontSize: 16, whiteSpace: "pre-wrap", maxWidth: "86%", overflowWrap: "anywhere" },
  aiAvatar: { width: 34, height: 34, borderRadius: "50%", color: "white", display: "flex", alignItems: "center", justifyContent: "center", fontWeight: 950, flexShrink: 0, marginTop: 10 },
  aiHeader: { display: "flex", flexDirection: "column", gap: 2, marginBottom: 12, paddingBottom: 12, borderBottom: "1px solid rgba(120,120,120,0.18)" },
  bottomInput: { padding: "10px 0 8px", flexShrink: 0 },
  messageLine: { lineHeight: 1.7, margin: "2px 0" },
  numberedLine: { margin: "8px 0", lineHeight: 1.65, fontWeight: 650 },
  bulletLine: { margin: "6px 0", lineHeight: 1.65 },
  codeBlock: { borderRadius: 16, padding: "16px 18px", margin: "14px 0", overflowX: "auto", fontSize: 13, lineHeight: 1.55, whiteSpace: "pre-wrap", background: "#0f172a", color: "#e5e7eb" },
  attachmentBox: { marginTop: 10, padding: "10px 12px", borderRadius: 12, background: "rgba(120,120,120,0.10)", fontSize: 13 },
  overlay: { position: "fixed", inset: 0, background: "rgba(0,0,0,0.55)", display: "flex", justifyContent: "center", alignItems: "center", zIndex: 1000, padding: 16 },
  checklistModal: { borderRadius: 24, height: "min(860px, calc(100dvh - 32px))", display: "flex", flexDirection: "column", overflow: "hidden", boxShadow: "0 30px 70px rgba(0,0,0,0.28)", padding: 28 },
  modalHeader: { display: "flex", alignItems: "center", justifyContent: "space-between", gap: 12, marginBottom: 16, flexShrink: 0 },
  backBtn: { width: 38, height: 38, minWidth: 38, padding: 0, background: "transparent", borderRadius: "50%", cursor: "pointer", fontWeight: 900, fontSize: 24, lineHeight: 1, display: "flex", alignItems: "center", justifyContent: "center" },
  modal: { borderRadius: 24, width: "min(620px, 100%)", height: "min(450px, calc(100dvh - 32px))", display: "flex", overflow: "hidden", boxShadow: "0 30px 60px rgba(0,0,0,0.25)" },
  modalSide: { width: 170, padding: 24, display: "flex", flexDirection: "column", gap: 15, flexShrink: 0 },
  modalMain: { flex: 1, minWidth: 0, padding: 32, display: "flex", flexDirection: "column", overflowY: "auto" },
  tabBtn: { textAlign: "left", border: "none", background: "transparent", cursor: "pointer", fontSize: 14, fontWeight: 850, padding: "8px 0" },
  settingsOverlay: {
    position: "fixed",
    inset: 0,
    background: "radial-gradient(circle at 30% 20%, rgba(96,165,250,0.18), transparent 30%), rgba(15,23,42,0.72)",
    backdropFilter: "blur(14px)",
    WebkitBackdropFilter: "blur(14px)",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    zIndex: 1000,
    padding: 18,
  },
  settingsModal: {
    width: "min(1180px, calc(100vw - 44px))",
    height: "min(760px, calc(100dvh - 44px))",
    minHeight: 520,
    display: "grid",
    gridTemplateColumns: "310px minmax(0, 1fr)",
    overflow: "hidden",
    borderRadius: 34,
    border: "1px solid rgba(226,232,240,0.38)",
    boxShadow: "0 34px 110px rgba(0,0,0,0.42)",
    background: "rgba(255,255,255,0.92)",
  },
  settingsSidePanel: {
    background: "linear-gradient(180deg, rgba(15,23,42,0.96), rgba(15,23,42,0.985))",
    padding: "38px 28px 30px",
    display: "flex",
    flexDirection: "column",
    justifyContent: "space-between",
    gap: 28,
    borderRight: "1px solid rgba(255,255,255,0.12)",
  },
  settingsTabsArea: { display: "flex", flexDirection: "column", gap: 16 },
  settingsTabBtn: {
    width: "100%",
    minHeight: 74,
    border: "1px solid transparent",
    borderRadius: 16,
    cursor: "pointer",
    display: "flex",
    alignItems: "center",
    gap: 16,
    padding: "13px 14px",
    textAlign: "left",
  },
  settingsTabIcon: {
    width: 42,
    height: 42,
    minWidth: 42,
    borderRadius: 14,
    border: "1px solid rgba(148,163,184,0.28)",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    fontSize: 26,
    lineHeight: 1,
    fontWeight: 900,
  },
  settingsTabText: { display: "flex", flexDirection: "column", gap: 3, fontSize: 17, fontWeight: 900 },
  settingsSideFooter: { marginTop: "auto" },
  settingsFooterLine: { height: 1, background: "rgba(148,163,184,0.2)", marginBottom: 24 },
  settingsInfoRow: { display: "flex", alignItems: "center", gap: 12, color: "rgba(226,232,240,0.76)", fontSize: 13, lineHeight: 1.35 },
  settingsInfoIcon: { width: 26, height: 26, minWidth: 26, borderRadius: "50%", border: "1px solid rgba(148,163,184,0.42)", display: "flex", alignItems: "center", justifyContent: "center", fontSize: 16 },
  settingsMainPanel: {
    position: "relative",
    padding: "58px 68px",
    overflowY: "auto",
    background: "#f8fbff",
  },
  settingsCloseBtn: {
    position: "absolute",
    top: 36,
    right: 38,
    width: 54,
    height: 54,
    borderRadius: "50%",
    border: "1px solid rgba(148,163,184,0.24)",
    background: "rgba(255,255,255,0.72)",
    boxShadow: "0 12px 30px rgba(15,23,42,0.10)",
    cursor: "pointer",
    fontSize: 34,
    lineHeight: 1,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
  },
  settingsHeader: { marginBottom: 54, paddingRight: 72 },
  settingsTitle: { margin: 0, fontSize: "clamp(34px, 4vw, 46px)", lineHeight: 1, fontWeight: 950, letterSpacing: -1.4 },
  settingsSubtitle: { margin: "12px 0 0", fontSize: 16, lineHeight: 1.45, color: "#64748b", fontWeight: 650 },
  settingsContentStack: { display: "flex", flexDirection: "column", gap: 26, maxWidth: 720 },
  settingsLabel: { fontSize: 12, fontWeight: 950, color: "#94a3b8", textTransform: "uppercase", letterSpacing: 0.7, marginBottom: 12, display: "block" },
  settingsInputCard: {
    minHeight: 74,
    borderRadius: 16,
    display: "flex",
    alignItems: "center",
    gap: 18,
    padding: "0 22px",
    boxShadow: "0 14px 32px rgba(15,23,42,0.06)",
  },
  settingsInputIcon: { width: 28, minWidth: 28, color: "#94a3b8", fontSize: 28, lineHeight: 1, display: "flex", alignItems: "center", justifyContent: "center" },
  settingsInlineInput: {
    width: "100%",
    minWidth: 0,
    border: "none",
    outline: "none",
    background: "transparent",
    fontSize: 18,
    fontWeight: 700,
    padding: "14px 0",
  },
  settingsLogoutBtn: {
    position: "relative",
    minHeight: 78,
    width: "100%",
    borderRadius: 16,
    border: "1px solid rgba(239,68,68,0.24)",
    background: "rgba(254,226,226,0.64)",
    color: "#ef4444",
    cursor: "pointer",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    gap: 16,
    fontSize: 17,
    fontWeight: 950,
    marginTop: 8,
  },
  settingsLogoutIcon: { position: "absolute", left: 28, fontSize: 31, lineHeight: 1 },
  settingsGuestNotice: { borderRadius: 18, padding: "14px 16px", display: "flex", flexDirection: "column", gap: 5, fontSize: 13, lineHeight: 1.45, color: "#92400e" },
  settingsThemeGrid: { display: "grid", gridTemplateColumns: "repeat(auto-fit, minmax(190px, 1fr))", gap: 14, maxWidth: 800 },
  settingsThemeOption: { padding: "15px 16px", minHeight: 60, borderRadius: 16, cursor: "pointer", display: "flex", alignItems: "center", gap: 13, fontSize: 14, fontWeight: 900 },
  label: { fontSize: 11, fontWeight: 800, color: "#94a3b8", textTransform: "uppercase", marginBottom: 8, display: "block" },
  input: { width: "100%", padding: 12, borderRadius: 12, marginBottom: 14, outline: "none", fontSize: 14 },
  primaryBtn: { width: "100%", padding: 15, border: "none", borderRadius: 14, color: "white", fontWeight: 850, cursor: "pointer", fontSize: 15, marginTop: 8 },
  secondaryBtn: { width: "100%", padding: 13, borderRadius: 14, background: "transparent", fontWeight: 850, cursor: "pointer", marginTop: 10 },
  errorBox: { marginTop: 12, padding: "10px 12px", borderRadius: 12, color: "#b91c1c", background: "#fee2e2", fontSize: 13, fontWeight: 700 },
  checklistLayout: { flex: 1, minHeight: 0, display: "grid", gridTemplateColumns: "minmax(340px, 0.9fr) minmax(360px, 1.1fr)", gap: 22, overflow: "hidden" },
  quickCalcLayout: { flex: 1, minHeight: 0, display: "grid", gridTemplateColumns: "minmax(390px, 0.95fr) minmax(430px, 1.05fr)", gap: 22, overflow: "hidden" },
  checklistFormArea: { overflowY: "auto", paddingRight: 6 },
  checklistResultsArea: { overflowY: "auto", display: "flex", flexDirection: "column", gap: 12, paddingRight: 6 },
  checklistGrid: { display: "grid", gridTemplateColumns: "1fr 1fr", gap: 12 },
  checklistTextarea: { width: "100%", minHeight: 92, padding: 12, borderRadius: 12, marginBottom: 14, outline: "none", fontSize: 14, resize: "vertical" },
  emptyChecklist: { borderRadius: 18, minHeight: 160, display: "flex", alignItems: "center", justifyContent: "center", textAlign: "center", opacity: 0.68, padding: 18, fontSize: 14 },
  resultCard: { borderRadius: 18, padding: 16, marginTop: 12 },
  resultTop: { display: "flex", alignItems: "center", justifyContent: "space-between", gap: 10, marginBottom: 8, fontSize: 14 },
  resultDetail: { margin: "0 0 10px", lineHeight: 1.5, fontSize: 13, opacity: 0.82 },
  resultSuggestion: { marginTop: 12, paddingLeft: 10, lineHeight: 1.5, fontSize: 13, fontWeight: 650 },
  warningBox: { marginTop: 14, borderRadius: 14, padding: 12, fontSize: 12, lineHeight: 1.5, opacity: 0.74 },
  formulaBlock: { borderRadius: 16, padding: 14, background: "rgba(120,120,120,0.08)", margin: "14px 0", overflowX: "auto", fontSize: 14, lineHeight: 1.6 },
  valueRow: { fontSize: 13, lineHeight: 1.45, margin: "6px 0" },
  finalBox: { marginTop: 16, padding: "12px 14px", borderRadius: 14, background: "rgba(120,120,120,0.08)", fontWeight: 850 },
  materialToolbar: { display: "grid", gridTemplateColumns: "1fr auto", gap: 10, alignItems: "center", marginBottom: 18 },
  addMaterialBtn: { border: "none", color: "white", borderRadius: 14, padding: "14px 16px", cursor: "pointer", fontWeight: 850, whiteSpace: "nowrap" },
  addMaterialPanel: { borderRadius: 18, padding: 18, marginBottom: 18, overflowY: "auto", maxHeight: 390 },
  addMaterialGrid: { display: "grid", gridTemplateColumns: "repeat(auto-fit, minmax(180px, 1fr))", gap: 12 },
  addMaterialTextarea: { width: "100%", minHeight: 70, borderRadius: 12, padding: 12, outline: "none", resize: "vertical", marginBottom: 14 },
  materialGrid: { flex: 1, overflowY: "auto", display: "grid", gridTemplateColumns: "repeat(auto-fit, minmax(330px, 1fr))", gap: 14, paddingRight: 4 },
  materialCard: { borderRadius: 18, padding: 18, lineHeight: 1.45, fontSize: 13 },
  materialHead: { display: "flex", alignItems: "center", justifyContent: "space-between", gap: 12, marginBottom: 12 },
  customTag: { display: "inline-flex", fontSize: 11, fontWeight: 850, opacity: 0.68 },
  smallDeleteMaterialBtn: { border: "none", color: "#991b1b", background: "#fee2e2", borderRadius: 999, padding: "8px 12px", cursor: "pointer", fontWeight: 850, fontSize: 12, whiteSpace: "nowrap" },
  materialCodes: { display: "grid", gridTemplateColumns: "1fr 1fr", gap: 6, fontSize: 12, marginBottom: 12, opacity: 0.82 },
  materialProps: { padding: 10, borderRadius: 12, background: "rgba(120,120,120,0.08)", marginBottom: 10, lineHeight: 1.5 },
  themeGrid: { display: "grid", gridTemplateColumns: "repeat(auto-fit, minmax(140px, 1fr))", gap: 10 },
  themeOption: { padding: 12, borderRadius: 14, cursor: "pointer", display: "flex", alignItems: "center", gap: 12, fontSize: 13, fontWeight: 800, background: "transparent" },
  themeDot: { width: 12, height: 12, borderRadius: "50%" },
  drawingLayout: { flex: 1, minHeight: 0, display: "grid", gridTemplateColumns: "minmax(380px, 0.95fr) minmax(430px, 1.05fr)", gap: 22, overflow: "hidden" },
  drawingUploadPanel: { borderRadius: 18, padding: 16, marginBottom: 18 },
  drawingUploadGridSingle: { display: "grid", gridTemplateColumns: "1fr", gap: 10, marginTop: 12 },
  drawingUploadBtn: { minHeight: 72, borderRadius: 16, background: "transparent", cursor: "pointer", display: "flex", flexDirection: "column", alignItems: "center", justifyContent: "center", gap: 4, fontWeight: 850, fontSize: 14 },
  drawingFileCard: { display: "flex", alignItems: "flex-start", gap: 10, borderRadius: 16, padding: 12, marginTop: 12 },
  drawingPreviewImage: { width: "100%", maxHeight: 180, objectFit: "contain", borderRadius: 12, marginTop: 10, background: "rgba(120,120,120,0.08)" },
  drawingPreviewPanel: { borderRadius: 18, padding: 16, marginBottom: 12 },
  drawingPreviewTop: { display: "flex", alignItems: "flex-start", justifyContent: "space-between", gap: 12, marginBottom: 12 },
  previewBadge: { minWidth: 28, height: 28, borderRadius: 999, color: "white", display: "inline-flex", alignItems: "center", justifyContent: "center", fontSize: 12, fontWeight: 900 },
  realDrawingPreviewBox: { position: "relative", width: "100%", minHeight: 360, maxHeight: 520, borderRadius: 14, overflow: "hidden", marginBottom: 12, display: "flex", alignItems: "center", justifyContent: "center" },
  realDrawingPreviewImage: { width: "100%", height: "100%", maxHeight: 520, objectFit: "contain", display: "block" },
  noIssuesOverlay: { position: "absolute", inset: 0, display: "flex", alignItems: "center", justifyContent: "center", fontSize: 13, fontWeight: 800, opacity: 0.55, pointerEvents: "none", textAlign: "center", padding: 20 },
  issueMarker: { position: "absolute", transform: "translate(-50%, -50%)", width: 26, height: 26, borderRadius: "50%", color: "white", display: "flex", alignItems: "center", justifyContent: "center", fontWeight: 950, fontSize: 15, boxShadow: "0 8px 22px rgba(0,0,0,0.28)", border: "2px solid rgba(255,255,255,0.85)" },
  issueList: { display: "flex", flexDirection: "column", gap: 8 },
  issueRow: { display: "flex", alignItems: "flex-start", gap: 8, fontSize: 12, lineHeight: 1.35 },
  issueDot: { width: 9, height: 9, borderRadius: "50%", marginTop: 5, flexShrink: 0 },
  emptyText: { fontSize: 12, opacity: 0.6, padding: 8 },
  quickResultShell: {
  borderRadius: 22,
  padding: 18,
  display: "flex",
  flexDirection: "column",
  gap: 16,
  boxShadow: "0 18px 50px rgba(0,0,0,0.22)",
},

quickHero: {
  display: "flex",
  alignItems: "flex-start",
  justifyContent: "space-between",
  gap: 16,
  paddingBottom: 14,
  borderBottom: "1px solid rgba(120,120,120,0.18)",
},

quickHeroText: {
  minWidth: 0,
  flex: 1,
},

quickEyebrow: {
  fontSize: 11,
  fontWeight: 950,
  textTransform: "uppercase",
  letterSpacing: 0.8,
  opacity: 0.55,
  marginBottom: 6,
},

quickHeroTitle: {
  margin: 0,
  fontSize: 19,
  lineHeight: 1.2,
  fontWeight: 950,
  letterSpacing: -0.4,
},

quickHeroSubtitle: {
  margin: "8px 0 0",
  fontSize: 13,
  lineHeight: 1.55,
  opacity: 0.72,
},

quickOutcomeBadge: {
  flexShrink: 0,
  minWidth: 92,
  minHeight: 38,
  borderRadius: 999,
  display: "flex",
  alignItems: "center",
  justifyContent: "center",
  fontSize: 13,
  fontWeight: 950,
  letterSpacing: 0.4,
  padding: "8px 13px",
},

quickMetricsGrid: {
  display: "grid",
  gridTemplateColumns: "repeat(3, minmax(0, 1fr))",
  gap: 10,
},

quickMetricCard: {
  borderRadius: 18,
  padding: "14px 14px 13px",
  minHeight: 98,
  display: "flex",
  flexDirection: "column",
  justifyContent: "space-between",
  gap: 8,
},

quickMetricLabel: {
  fontSize: 11,
  fontWeight: 900,
  textTransform: "uppercase",
  opacity: 0.58,
  lineHeight: 1.25,
},

quickMetricValue: {
  fontSize: 22,
  lineHeight: 1.05,
  fontWeight: 950,
  letterSpacing: -0.6,
},

quickMetricSub: {
  fontSize: 11,
  lineHeight: 1.3,
  opacity: 0.55,
},

quickFinalBanner: {
  borderRadius: 20,
  padding: 16,
  display: "flex",
  alignItems: "flex-start",
  gap: 13,
},

quickFinalIcon: {
  width: 32,
  height: 32,
  minWidth: 32,
  borderRadius: "50%",
  color: "white",
  display: "flex",
  alignItems: "center",
  justifyContent: "center",
  fontWeight: 950,
  fontSize: 18,
  marginTop: 2,
},

quickFinalTitle: {
  margin: 0,
  fontSize: 18,
  lineHeight: 1.2,
  fontWeight: 950,
},

quickFinalText: {
  margin: "7px 0 0",
  fontSize: 14,
  lineHeight: 1.55,
  fontWeight: 700,
},

quickFinalWarning: {
  margin: "9px 0 0",
  fontSize: 13,
  lineHeight: 1.45,
  fontWeight: 750,
  opacity: 0.86,
},

quickFinalOk: {
  margin: "9px 0 0",
  fontSize: 13,
  lineHeight: 1.45,
  fontWeight: 750,
  opacity: 0.86,
},

quickSectionBadge: {
  borderRadius: 18,
  padding: "13px 15px",
  display: "flex",
  flexDirection: "column",
  gap: 4,
},

quickDetailSection: {
  borderRadius: 18,
  padding: 15,
},

quickDetailTitle: {
  margin: "0 0 12px",
  fontSize: 14,
  fontWeight: 950,
  letterSpacing: -0.2,
},

quickDetailList: {
  display: "flex",
  flexDirection: "column",
  gap: 8,
},

quickStepsBox: {
  borderRadius: 18,
  padding: 15,
},

quickStepsList: {
  display: "flex",
  flexDirection: "column",
  gap: 12,
},

quickStepItem: {
  display: "grid",
  gridTemplateColumns: "28px 1fr",
  gap: 10,
  alignItems: "flex-start",
  fontSize: 13,
  lineHeight: 1.45,
},

quickStepNumber: {
  width: 24,
  height: 24,
  borderRadius: "50%",
  color: "white",
  display: "flex",
  alignItems: "center",
  justifyContent: "center",
  fontSize: 12,
  fontWeight: 950,
  marginTop: 2,
},

quickStepText: {
  margin: "4px 0 0",
  fontSize: 13,
  lineHeight: 1.45,
  opacity: 0.78,
},
  
quickDetailRow: {
  display: "flex",
  alignItems: "flex-start",
  gap: 8,
  fontSize: 13,
  lineHeight: 1.45,
  fontWeight: 650,
},

quickDot: {
  width: 7,
  height: 7,
  borderRadius: "50%",
  marginTop: 7,
  flexShrink: 0,
},

quickFormulaSection: {
  borderRadius: 18,
  padding: 15,
},

quickFormulaGrid: {
  display: "grid",
  gridTemplateColumns: "repeat(auto-fit, minmax(170px, 1fr))",
  gap: 8,
},

quickFormulaChip: {
  borderRadius: 13,
  padding: "10px 12px",
  fontSize: 13,
  lineHeight: 1.35,
  fontWeight: 800,
  fontFamily: "ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, monospace",
},

  quickSuggestionBox: {
  borderRadius: 18,
  padding: 14,
  display: "flex",
  flexDirection: "column",
  gap: 12,
},

quickSuggestionHeader: {
  display: "flex",
  alignItems: "flex-start",
  justifyContent: "space-between",
  gap: 12,
},

quickSuggestionKicker: {
  display: "block",
  fontSize: 10,
  fontWeight: 950,
  textTransform: "uppercase",
  letterSpacing: 0.7,
  color: "#f97316",
  marginBottom: 4,
},

quickSuggestionTitle: {
  margin: 0,
  fontSize: 16,
  lineHeight: 1.2,
  fontWeight: 950,
},

quickSuggestionBadge: {
  flexShrink: 0,
  borderRadius: 999,
  padding: "7px 11px",
  background: "rgba(249,115,22,0.14)",
  color: "#f97316",
  border: "1px solid rgba(249,115,22,0.55)",
  fontSize: 13,
  fontWeight: 950,
},

quickSuggestionGrid: {
  display: "grid",
  gridTemplateColumns: "repeat(3, minmax(0, 1fr))",
  gap: 8,
},

quickSuggestionMiniCard: {
  borderRadius: 14,
  padding: "10px 11px",
  background: "rgba(120,120,120,0.08)",
  display: "flex",
  flexDirection: "column",
  gap: 5,
},

quickSuggestionMiniLabel: {
  fontSize: 10,
  fontWeight: 950,
  textTransform: "uppercase",
  opacity: 0.55,
},

quickSuggestionMiniValue: {
  fontSize: 14,
  fontWeight: 950,
  lineHeight: 1.2,
},

quickSuggestionNote: {
  margin: 0,
  fontSize: 12,
  lineHeight: 1.45,
  opacity: 0.68,
},
  

quickNotesBox: {
  borderRadius: 18,
  padding: 15,
},

quickNoteText: {
  margin: "8px 0 0",
  fontSize: 13,
  lineHeight: 1.5,
  fontWeight: 700,
  opacity: 0.82,
},
  projectCreateFixedPanel: { position: "sticky", top: 0, zIndex: 5 },
  projectCreateCompactHeader: { display: "flex", alignItems: "flex-start", justifyContent: "space-between", gap: 14, marginBottom: 10 },
  projectCreateCompactGrid: { display: "grid", gridTemplateColumns: "1fr 1.2fr", gap: 12, alignItems: "end" },
  projectCreateCompactButton: { width: 190, marginTop: 0, flexShrink: 0 },
  projectLayout: { flex: 1, minHeight: 0, display: "grid", gridTemplateColumns: "minmax(300px, 0.72fr) minmax(520px, 1.28fr)", gap: 18, overflow: "hidden" },
  projectLeft: { overflowY: "auto", display: "flex", flexDirection: "column", gap: 14, paddingRight: 4 },
  projectRight: { overflowY: "auto", display: "flex", flexDirection: "column", gap: 14, paddingRight: 6 },
  projectPanel: { borderRadius: 20, padding: 16, boxShadow: "0 12px 34px rgba(0,0,0,0.10)" },
  projectToolButton: { width: "100%", textAlign: "left", borderRadius: 16, padding: 14, marginTop: 10, cursor: "pointer", display: "flex", flexDirection: "column", gap: 5, fontWeight: 800 },
  projectTitle: { margin: "0 0 12px", fontSize: 16, fontWeight: 950, letterSpacing: -0.3 },
  projectListItem: { borderRadius: 16, padding: 10, display: "flex", alignItems: "center", gap: 10, marginBottom: 8 },
  projectListMain: { flex: 1, minWidth: 0, background: "transparent", border: "none", textAlign: "left", cursor: "pointer", display: "flex", flexDirection: "column", gap: 3, color: "inherit" },
  projectHeaderCard: { borderRadius: 16, padding: 14, background: "rgba(120,120,120,0.10)", display: "flex", flexDirection: "column", gap: 5, marginBottom: 12 },
  projectSavedItem: { borderRadius: 16, padding: 14, marginBottom: 10 },
  projectMiniCard: { borderRadius: 16, padding: 12, marginTop: 10, display: "flex", flexDirection: "column", gap: 4, fontSize: 13 },
  projectStatsGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(6, minmax(0, 1fr))",
    gap: 8,
    marginBottom: 12,
  },
  projectStatCard: {
    borderRadius: 14,
    padding: "10px 8px",
    display: "flex",
    flexDirection: "column",
    gap: 4,
    textAlign: "center",
    fontSize: 12,
    fontWeight: 850,
  },
  projectActionGrid: {
    display: "grid",
    gridTemplateColumns: "1fr 1fr",
    gap: 10,
    marginBottom: 12,
  },
  projectTabs: {
    display: "flex",
    flexWrap: "wrap",
    gap: 8,
    margin: "12px 0",
  },
  projectTabBtn: {
    borderRadius: 999,
    padding: "8px 11px",
    fontSize: 12,
    fontWeight: 900,
    cursor: "pointer",
    display: "flex",
    alignItems: "center",
    gap: 6,
  },
  projectMemoryIntro: {
    borderRadius: 16,
    padding: 12,
    display: "flex",
    flexDirection: "column",
    gap: 5,
    fontSize: 13,
    lineHeight: 1.45,
    marginBottom: 12,
  },
  projectDecisionBox: {
    borderRadius: 18,
    padding: 14,
    display: "flex",
    flexDirection: "column",
    gap: 10,
    marginBottom: 12,
  },
  projectMiniTextarea: {
    width: "100%",
    minHeight: 90,
    borderRadius: 14,
    padding: "11px 12px",
    outline: "none",
    resize: "vertical",
    fontSize: 14,
    lineHeight: 1.5,
  },
  projectInlineDataGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fit, minmax(120px, 1fr))",
    gap: 8,
    marginTop: 10,
    fontSize: 12,
    fontWeight: 850,
    opacity: 0.82,
  },


};
